name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git /home/runner/theos
      - name: Build
        run: |
          export THEOS=/home/runner/theos
          export PATH=$THEOS/bin:$PATH
          make
          make package
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: packages/*.deb
